### ISSUE TITLE
GitHub issues pagination limits the list to 30 issues

### ISSUE THREAD

**Issue by cuerty** [pignacio/issue2branch#9]
According to https://developer.github.com/v3/#pagination:

> Requests that return multiple items will be paginated to 30 items by default.

Adding a "&per_page=100" to the URL "fixes" this problem (moving the new limit to 100).

**Comment by pignacio** [comment]
In version 0.0.3 list limits can be handled via config:

```
#.issue2branch.config

[list]
limit = 100  

#[redmine]:list_limit does not work anymore
```

or via argument

`% issue2branch -l --limit 123`
